<html>
<head>
<title>[[WIKI]] - [[TITLE]]</title>
</head>
<body>
<h1>[[TITLE]]</h1>
<a href="[[BASE]]">Front Page</a>
<hr>

[[CONTENT]]
<hr>
[[AUTHOR]] @ [[DATE]]<br>You Are: [[USER]] Identified by [[AUTH]] [ <a href="[[URL]]?action=login">Login</a> | <a href="[[URL]]?action=newUser">New User</a> ]<br>Generated by [[AQWIKI]]
</body>
</html>